### ISSUE TITLE
TOKEN

### ISSUE THREAD

**Issue by saphali** [dotochki-com/api#1]
Здравствуйте. А какой token использовать для теста, когда нет рабочего?

**Comment by dumuro** [comment]
Добрый день. 
Добавили возможность создание токена.

**Comment by saphali** [comment]
Спасибо.

**Comment by saphali** [comment]
Почему-то запрос на https://test.dotochki.ru/api/v2/order/login/ выдает не xml и не json:
An Error occurred while handling another error:
exception 'yii\base\InvalidParamException' with message 'Response content must not be an array.' in /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/Response.php:960
Stack trace:
#0 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/Response.php(311): yii\web\Response->prepare()
#1 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\Response->send()
#2 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(109): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#4 {main}
Previous exception:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request: api/v2/order/login' in /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Controller.php:125
Stack trace:
#0 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('login', Array)
#1 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('api/v2/order/lo...', Array)
#2 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /home/test/vhosts/site/test/public/index.php(33): yii\base\Application->run()
#4 {main}

Next exception 'yii\web\NotFoundHttpException' with message 'Страница не найдена.' in /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/Application.php:96
Stack trace:
#0 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /home/test/vhosts/site/test/public/index.php(33): yii\base\Application->run()
#2 {main}

Следовательно, невозможно получить token.

**Comment by dumuro** [comment]
Мы поправили результат ответа. Теперь от в JSON.
Вы пытаетесь вызвать не существующий метод.

> https://dotochki.com/api/v2/login/index/ [POST]

**Comment by saphali** [comment]
Спасибо. Отправляю данные:

POST https://test.dotochki.ru/api/v2/order/login
Content-Type: application/x-www-form-urlencoded
login=TEST&password=TEST

и в ответ получаю:
 -- response --
404 Not Found
Server:  nginx
Date:  Mon, 11 Apr 2016 12:48:31 GMT
Content-Type:  application/json; charset=UTF-8
X-Firefox-Spdy:  3.1

{"success":false,"data":"Method Not Found"}


Что я не так делаю?

**Comment by saphali** [comment]
Все. Ошибку понял. Запрос делал не на https://test.dotochki.com/api/v2/login/index/

**Comment by saphali** [comment]
Тогда Api.php нужно подправить, чтобы запрос делал не на https://test.dotochki.ru/api/v2/order/login, а на https://test.dotochki.com/api/v2/login/index/

Спасибо.

**Comment by saphali** [comment]
При использовании произвольных значений пары логин и пароль получая в ответе:
{
    "success": true,
    "data": {
        "token": false
    }
}
Что нужно или какие данные (логин и пароль) нужно использовать для того, чтобы получить token для теста?

**Comment by dumuro** [comment]
Выполнить регистрацию на http://test.dotochki.com/client/registry/person/

**Comment by saphali** [comment]
Выполнил регистрацию. Регистрировался как корпоративный так и как частный. Отправлял в качестве логина эл. почту на которую регистрировался и пароль аккаунта для входа на  http://test.dotochki.com/ и результат тот же:

POST https://dotochki.com/api/v2/login/index/
Accept: application/json
Content-Type: application/x-www-form-urlencoded
login=emeil_который_использовался_при_регистрации&password=qazwsx

 -- response --
200 OK
Server:  nginx
Date:  Mon, 11 Apr 2016 13:59:52 GMT
Content-Type:  application/json; charset=UTF-8
X-Firefox-Spdy:  3.1

{"success":true,"data":{"token":false}}

**Comment by saphali** [comment]
Странно, когда не передаются параметры выдает token:

POST https://dotochki.com/api/v2/login/index/
Accept: application/json
Content-Type: application/x-www-form-urlencoded

 -- response --
200 OK
Server:  nginx
Date:  Mon, 11 Apr 2016 14:08:34 GMT
Content-Type:  application/json; charset=UTF-8
X-Firefox-Spdy:  3.1

{"success":true,"data":{"token":"Q7sh81CqtoFlShx7ScJz4FldWPWwi84ucQIce5jZCNdDoxRnEUHfuxsVR3M9TqsLBqT8Ojs2GdRnG7xHHo6msXBL3ENwt5CYHaPyKHW_Ambz9qbfqXi2LWgDdAaDD5Q-"}}

**Comment by dumuro** [comment]
Проверили метод. Работает.

**Comment by saphali** [comment]
Здравствуйте.
Борюсь с ошибкой "PHP Notice - A non well formed numeric value encountered". Полный ответ от сервера:
array(2) {
  ["success"]=>
  bool(false)
  ["data"]=>
  array(7) {
    ["name"]=>
    string(10) "PHP Notice"
    ["message"]=>
    string(43) "A non well formed numeric value encountered"
    ["code"]=>
    int(8)
    ["type"]=>
    string(23) "yii\base\ErrorException"
    ["file"]=>
    string(68) "/home/test/vhosts/site/test/protected/modules/office/models/Call.php"
    ["line"]=>
    int(89)
    ["stack-trace"]=>
    array(17) {
      [0]=>
      string(116) "#0 [internal function]: yii\base\ErrorHandler->handleError(8, 'A non well form...'
, '/home/test/vhos...', 89, Array)"
      [1]=>
      string(130) "#1 /home/test/vhosts/site/test/protected/modules/office/models/Call.php(89): socket_connect
(Resource id #14, '10.7.1.44', '8081/')"
      [2]=>
      string(149) "#2 /home/test/vhosts/site/test/protected/helpers/ActionHelper.php(1011): app\modules
\office\models\Call::pushMessage('logist', Array, 0, 'order_add')"
      [3]=>
      string(112) "#3 /home/test/vhosts/site/test/protected/models/Order.php(1032): app\helpers\ActionHelper
::newOrderNotify(21681)"
      [4]=>
      string(128) "#4 /home/test/vhosts/site/test/protected/modules/api/modules/v2/models/Order.php(405
): app\models\Order->afterSave(false, Array)"
      [5]=>
      string(155) "#5 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php
(739): app\modules\api\modules\v2\models\Order->afterSave(false, Array)"
      [6]=>
      string(132) "#6 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(533
): yii\db\BaseActiveRecord->updateInternal(NULL)"
      [7]=>
      string(130) "#7 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php
(595): yii\db\ActiveRecord->update(true, NULL)"
      [8]=>
      string(135) "#8 /home/test/vhosts/site/test/protected/modules/api/modules/v2/controllers/order
/UpdateAction.php(32): yii\db\BaseActiveRecord->save()"
      [9]=>
      string(95) "#9 [internal function]: app\modules\api\modules\v2\controllers\order\UpdateAction-
>run('21681')"
      [10]=>
      string(117) "#10 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Action.php(92)
: call_user_func_array(Array, Array)"
      [11]=>
      string(125) "#11 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Controller.php
(154): yii\base\Action->runWithParams(Array)"
      [12]=>
      string(131) "#12 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Module.php(454
): yii\base\Controller->runAction('update', Array)"
      [13]=>
      string(142) "#13 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/web/Application.php
(84): yii\base\Module->runAction('api/v2/order/up...', Array)"
      [14]=>
      string(148) "#14 /home/test/vhosts/site/test/protected/vendor/yiisoft/yii2/base/Application.php
(375): yii\web\Application->handleRequest(Object(yii\web\Request))"
      [15]=>
      string(81) "#15 /home/test/vhosts/site/test/public/index.php(33): yii\base\Application->run()"

      [16]=>
      string(10) "#16 {main}"
    }
  }
Данные которые отправляются на сервер от магазина:
array(17) {
  ["address_from"]=>
  string(37) "Москва, ул. Ленина, 119"
  ["phone_from"]=>
  string(11) "79998887774"
  ["client_from"]=>
  string(27) "Бинаспорт Олег"
  ["address_to"]=>
  string(44) "САНКТ-ПЕТЕРБУРГ, Lenina st, 30"
  ["phone_to"]=>
  string(11) "74951510744"
  ["client_to"]=>
  string(10) "Alex Vango"
  ["sender_time_from"]=>
  string(19) "2016-04-20 09:00:00"
  ["sender_time_to"]=>
  string(19) "2016-04-20 10:00:00"
  ["recipient_time_from"]=>
  string(19) "2016-04-20 18:00:00"
  ["recipient_time_to"]=>
  string(19) "2016-04-20 19:00:00"
  ["weight"]=>
  float(2)
  ["description"]=>
  string(18) "Заказ №6356"
  ["comment_from"]=>
  string(0) ""
  ["comment_to"]=>
  string(0) ""
  ["sender_value"]=>
  int(0)
  ["receiver_value"]=>
  float(580)
  ["order_items"]=>
  array(1) {
    [0]=>
    array(4) {
      ["name"]=>
      string(40) "С071 (Размер: 2 спальный)"
      ["weight"]=>
      float(2)
      ["price_to_take"]=>
      string(6) "4797.4"
      ["quantity"]=>
      string(1) "2"
    }
  }
}
Никак не могу понять, что не так. Ошибок по идее быть не должно.

**Comment by dumuro** [comment]
Добрый день! Прошу прощения за заминку.
Поправили. **FIX**

**Comment by saphali** [comment]
Здравствуйте. Спасибо, работает.

**Comment by saphali** [comment]
Также возник еще вопрос. Почему, когда извлекаю информацию о заказе методом **view**, то разница во времени забора и доставки составляет 1 час.
![2016-04-21_10-36-51](https://cloud.githubusercontent.com/assets/6737017/14701551/a76f0afa-07ae-11e6-9cbd-9c4a18d12c41.png)

**Comment by dumuro** [comment]
Была ошибка в определении Locale. 
Поправили, спасибо.

**Comment by saphali** [comment]
Проверил. Разница в 1 час все еще есть.

**Comment by dumuro** [comment]
Проверьте.

**Comment by saphali** [comment]
Спасибо. Все в порядке.
